planner:
  nominalvel_mpersecs: 0.5

visualizations:
  final_path: true
  expansions: true

robot_description:
  radius: 0.3

collision_space:
  reference_frame: map
  resolution: 0.02
  collision_map_topic: collision_map_occ    #ignored

  occupancy_grid:
    origin_x: 0.0
    origin_y: 0.0   # 1.25 - changed to see if there is a bug in the distance_field class
    origin_z: 0.0   # -0.05 - ditto
    size_x: 10.0
    size_y: 6.0
    size_z: 2.0

reference_frame: map