swarm_description:
    # the relative positions of each robot in the swarm is computed from this initial config.
    # To make it easier, leave one robot at the origin and define the rest with respect to this one; the NUM_ROBOTS param is also computed from this list.
    # star config - 5 robots
    # relative_positions: [0,0,  0.9,0,  0.9,0.9,  0.45,0.45,  0,0.9]
    # batman!
    relative_positions: [0,0, -0.34,0.34, 0.34,0.34, -0.49,-0.29, 0.49,-0.29, -0.98,-0.58, 0.98,-0.58, -1.21,0.05, 1.21,0.05, -1.69,-0.34, -1.82,-0.92, -1.57,-1.37, -1.1,-1.78, -0.6,-1.22, 0,-1.5, 1.69,-0.34, 1.82,-0.92, 1.57,-1.37, 1.1,-1.78, 0.6,-1.22, 0,-0.77]
    # the number of robots that can act as leaders
    num_leaders: 8
    # this indexes into the relative_positions defined above. We want the indices of the robots that can act as leaders, starting with 0.
    leader_ids: [1, 2, 7, 10, 12, 8, 16, 18]