debug:
    logging:
        configuration: debug
        initialization: debug
        collision_space: debug
        kinematics: info
        hashmanager: info
        search: info
        motionprimitives: info
        heuristics: info
        pathpostprocessor: info
        policygenerator: info
