debug:
    logging:
        configuration: debug
        initialization: debug
        collision_space: debug
        kinematics: info
        hashmanager: info
        search: debug
        motionprimitives: debug
        heuristics: info
        pathpostprocessor: debug
